apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $.Chart.Name }}-{{ .Values.environment }}"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: discord-formation
  template:
    metadata:
      labels:
        app: discord-formation
    spec:
      containers:
        - name: discord-formation
          image: "{{ $.Values.image }}:{{ $.Chart.Version }}"
          env:
            - name: ENVIRONMENT
              value: "{{ $.Values.environment }}"
            - name: PUSHGATEWAY_URL
              value: "{{ $.Values.pushgatewayUrl }}"
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-formation.config.{{ $.Values.environment }}
                  key: token
      terminationGracePeriodSeconds: 5
