name: Test

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false

  test:
    name: Test
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 600000

      - name: Run Tests
        run: yarn test
